package forme;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Korisnik
 */
import controller.Controller;
import java.util.List;
import javax.swing.JOptionPane;
import model.*;

public class AngazovanjeForma extends javax.swing.JFrame {

    Profesor odabrani;

    /**
     * Creates new form AngazovanjeForma
     */
    public AngazovanjeForma() {
        initComponents();
        List<Profesor> profesori = Controller.getInstance().vratiProfesore();
        jTableProfesori.setModel(new ModelTabeleProfesor(profesori));
        popuniComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfesori = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePredmeti = new javax.swing.JTable();
        jComboBoxPredmet = new javax.swing.JComboBox<>();
        jButtonUnesi = new javax.swing.JButton();
        jButtonPrikazi = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProfesori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProfesori);

        jTablePredmeti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablePredmeti);

        jButtonUnesi.setText("Unesi predmet");
        jButtonUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnesiActionPerformed(evt);
            }
        });

        jButtonPrikazi.setText("Prikazi predmete");
        jButtonPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi angazovanje");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonPrikazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonUnesi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonObrisi)
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPrikazi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUnesi))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonObrisi)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnesiActionPerformed

        int sr = jTableProfesori.getSelectedRow();
        if (sr == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite profesora");
            return;
        }
        
        
        
        ModelTabeleProfesor mp = (ModelTabeleProfesor) jTableProfesori.getModel();
        odabrani = mp.getLista().get(sr);

        Predmet pred = (Predmet) jComboBoxPredmet.getSelectedItem();

        int broj = Controller.getInstance().brojAng(odabrani);

        if (broj < 3) {
            boolean vecPostoji=Controller.getInstance().postojiAngazovanje(odabrani, pred);
            boolean uspesno = Controller.getInstance().dodajAngazovanje(odabrani, pred);
            if(vecPostoji){
                JOptionPane.showMessageDialog(this, "Angazovanje vec postoji u bazi");
                
                return;
            }
            if (uspesno) {
                JOptionPane.showMessageDialog(this, "Uneto novo angazovanje");
                osveziTabeluPredmet();

            } else {
                JOptionPane.showMessageDialog(this, "Greska pri unosu angazovanja");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Greska vec ima tri angazovanja");
            return;
        }


    }//GEN-LAST:event_jButtonUnesiActionPerformed

    private void jButtonPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziActionPerformed

        int sr = jTableProfesori.getSelectedRow();
        if (sr == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite profesora");
            return;
        }
        ModelTabeleProfesor mt = (ModelTabeleProfesor) jTableProfesori.getModel();

        odabrani = mt.getLista().get(sr);

        List<Predmet> predmeti = Controller.getInstance().vratiPredmetePoProfesoru(odabrani);

        ModelTabelePredmet mtp = new ModelTabelePredmet(predmeti);
        jTablePredmeti.setModel(mtp);

    }//GEN-LAST:event_jButtonPrikaziActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed

        int sr = jTablePredmeti.getSelectedRow();
        if (sr == -1) {
            JOptionPane.showMessageDialog(this, "Odaberite angazovanje");
            return;
        }

        ModelTabelePredmet mtp = (ModelTabelePredmet) jTablePredmeti.getModel();
        Predmet p = mtp.getLista().get(sr);

        

        int odg = JOptionPane.showConfirmDialog(this, "Da li zelite da obrisete angazovanje?", "Provera", JOptionPane.YES_NO_OPTION);
        if (odg==JOptionPane.YES_OPTION){
            boolean uspesno = Controller.getInstance().obrisiAngazovanje(odabrani, p);
            if(uspesno){
                JOptionPane.showMessageDialog(this, "Obrisano angazovanje");
            }
            else{
                JOptionPane.showMessageDialog(this, "Greska pri brisanju angazovanja");
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AngazovanjeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AngazovanjeForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPrikazi;
    private javax.swing.JButton jButtonUnesi;
    private javax.swing.JComboBox<Predmet> jComboBoxPredmet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePredmeti;
    private javax.swing.JTable jTableProfesori;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        List<Predmet> predmeti = Controller.getInstance().vratiPredmete();

        for (Predmet p : predmeti) {
            jComboBoxPredmet.addItem(p);
        }

    }

    private void osveziTabeluPredmet() {
        List<Predmet> predmeti=Controller.getInstance().vratiPredmete();
        ModelTabelePredmet mp=new ModelTabelePredmet(predmeti);
        jTablePredmeti.setModel(mp);
    
    }

}
